version: '3'
services:
    api:
        build: ./api
        ports:
        - "8080:8080"
        volumes:
        - .:/code
        - logvolume01:/var/log
    mongo:
        image: "mongo:4.1.13"
        ports:
        - "27017:27017"
volumes:
    logvolume01: {}